(function() {
const quizData = {
  "test_name": "FIA Computer-Based Test - Practice MCQs",
  "based_on_syllabus": {
    "General Knowledge": "45%",
    "English": "30%",
    "Mathematics": "15%",
    "Pakistan Studies": "5%",
    "Islamiat": "5%"
  },
  "total_questions": 100,
  "questions": [
    {"id": 1, "subject": "General Knowledge", "question": "Who is the founder of Pakistan?", "options": {"A": "Allama Iqbal", "B": "Quaid-e-Azam Muhammad Ali Jinnah", "C": "Liaquat Ali Khan", "D": "Sir Syed Ahmed Khan"}, "answer": "B"},
    {"id": 2, "subject": "General Knowledge", "question": "Which organization's headquarters is in New York?", "options": {"A": "WHO", "B": "UNO", "C": "UNESCO", "D": "IMF"}, "answer": "B"},
    {"id": 3, "subject": "General Knowledge", "question": "The currency of Japan is called?", "options": {"A": "Won", "B": "Yuan", "C": "Yen", "D": "Ringgit"}, "answer": "C"},
    {"id": 4, "subject": "General Knowledge", "question": "Which is the largest ocean in the world?", "options": {"A": "Atlantic Ocean", "B": "Indian Ocean", "C": "Arctic Ocean", "D": "Pacific Ocean"}, "answer": "D"},
    {"id": 5, "subject": "General Knowledge", "question": "SAARC was established in which year?", "options": {"A": "1980", "B": "1985", "C": "1990", "D": "1975"}, "answer": "B"},
    {"id": 6, "subject": "General Knowledge", "question": "Which country is known as the 'Land of Rising Sun'?", "options": {"A": "China", "B": "Japan", "C": "South Korea", "D": "Thailand"}, "answer": "B"},
    {"id": 7, "subject": "General Knowledge", "question": "The headquarters of WHO is located in?", "options": {"A": "New York", "B": "Paris", "C": "Geneva", "D": "Vienna"}, "answer": "C"},
    {"id": 8, "subject": "General Knowledge", "question": "Who invented the telephone?", "options": {"A": "Thomas Edison", "B": "Alexander Graham Bell", "C": "Nikola Tesla", "D": "James Watt"}, "answer": "B"},
    {"id": 9, "subject": "General Knowledge", "question": "Which is the smallest country in the world by area?", "options": {"A": "Monaco", "B": "San Marino", "C": "Vatican City", "D": "Liechtenstein"}, "answer": "C"},
    {"id": 10, "subject": "General Knowledge", "question": "The Great Wall is located in?", "options": {"A": "Japan", "B": "China", "C": "Mongolia", "D": "South Korea"}, "answer": "B"},
    {"id": 11, "subject": "General Knowledge", "question": "Which planet is known as the Red Planet?", "options": {"A": "Venus", "B": "Jupiter", "C": "Mars", "D": "Saturn"}, "answer": "C"},
    {"id": 12, "subject": "General Knowledge", "question": "Who was the first man to step on the Moon?", "options": {"A": "Buzz Aldrin", "B": "Neil Armstrong", "C": "Yuri Gagarin", "D": "John Glenn"}, "answer": "B"},
    {"id": 13, "subject": "General Knowledge", "question": "Which is the longest river in the world?", "options": {"A": "Amazon", "B": "Nile", "C": "Yangtze", "D": "Indus"}, "answer": "B"},
    {"id": 14, "subject": "General Knowledge", "question": "The Nobel Prize is awarded in which country?", "options": {"A": "Norway/Sweden", "B": "Switzerland", "C": "USA", "D": "UK"}, "answer": "A"},
    {"id": 15, "subject": "General Knowledge", "question": "Which is the largest continent by area?", "options": {"A": "Africa", "B": "Asia", "C": "North America", "D": "Europe"}, "answer": "B"},
    {"id": 16, "subject": "General Knowledge", "question": "FIFA World Cup 2022 was held in?", "options": {"A": "Russia", "B": "Brazil", "C": "Qatar", "D": "France"}, "answer": "C"},
    {"id": 17, "subject": "General Knowledge", "question": "The headquarters of IMF is located in?", "options": {"A": "Washington D.C.", "B": "New York", "C": "London", "D": "Geneva"}, "answer": "A"},
    {"id": 18, "subject": "General Knowledge", "question": "Which gas is most abundant in Earth's atmosphere?", "options": {"A": "Oxygen", "B": "Carbon Dioxide", "C": "Nitrogen", "D": "Hydrogen"}, "answer": "C"},
    {"id": 19, "subject": "General Knowledge", "question": "The Statue of Liberty is located in?", "options": {"A": "London", "B": "Paris", "C": "New York", "D": "Washington D.C."}, "answer": "C"},
    {"id": 20, "subject": "General Knowledge", "question": "Who wrote the theory of relativity?", "options": {"A": "Isaac Newton", "B": "Albert Einstein", "C": "Galileo Galilei", "D": "Stephen Hawking"}, "answer": "B"},
    {"id": 21, "subject": "General Knowledge", "question": "Which country has the largest population in the world (2026 estimate)?", "options": {"A": "China", "B": "India", "C": "USA", "D": "Indonesia"}, "answer": "B"},
    {"id": 22, "subject": "General Knowledge", "question": "The Olympics 2024 were held in which city?", "options": {"A": "Tokyo", "B": "Paris", "C": "London", "D": "Los Angeles"}, "answer": "B"},
    {"id": 23, "subject": "General Knowledge", "question": "Which vitamin is obtained from sunlight?", "options": {"A": "Vitamin A", "B": "Vitamin C", "C": "Vitamin D", "D": "Vitamin K"}, "answer": "C"},
    {"id": 24, "subject": "General Knowledge", "question": "The human heart has how many chambers?", "options": {"A": "2", "B": "3", "C": "4", "D": "5"}, "answer": "C"},
    {"id": 25, "subject": "General Knowledge", "question": "Which is the tallest mountain in the world?", "options": {"A": "K2", "B": "Mount Everest", "C": "Kilimanjaro", "D": "Nanga Parbat"}, "answer": "B"},
    {"id": 26, "subject": "General Knowledge", "question": "The currency of Saudi Arabia is?", "options": {"A": "Dinar", "B": "Riyal", "C": "Dirham", "D": "Rial"}, "answer": "B"},
    {"id": 27, "subject": "General Knowledge", "question": "Which is the fastest land animal?", "options": {"A": "Lion", "B": "Cheetah", "C": "Horse", "D": "Leopard"}, "answer": "B"},
    {"id": 28, "subject": "General Knowledge", "question": "World Environment Day is observed on?", "options": {"A": "5 June", "B": "22 April", "C": "1 May", "D": "10 December"}, "answer": "A"},
    {"id": 29, "subject": "General Knowledge", "question": "Which country gifted the Statue of Liberty to the USA?", "options": {"A": "UK", "B": "France", "C": "Spain", "D": "Italy"}, "answer": "B"},
    {"id": 30, "subject": "General Knowledge", "question": "The headquarters of Interpol is located in?", "options": {"A": "Geneva", "B": "Lyon", "C": "Paris", "D": "Brussels"}, "answer": "B"},
    {"id": 31, "subject": "General Knowledge", "question": "Which is the largest desert in the world?", "options": {"A": "Sahara", "B": "Thar", "C": "Gobi", "D": "Antarctic Desert"}, "answer": "D"},
    {"id": 32, "subject": "General Knowledge", "question": "The metal used in making electrical wires is mostly?", "options": {"A": "Iron", "B": "Copper", "C": "Aluminum", "D": "Zinc"}, "answer": "B"},
    {"id": 33, "subject": "General Knowledge", "question": "Which country hosted the 2023 Cricket World Cup?", "options": {"A": "England", "B": "Australia", "C": "India", "D": "South Africa"}, "answer": "C"},
    {"id": 34, "subject": "General Knowledge", "question": "The study of birds is called?", "options": {"A": "Zoology", "B": "Botany", "C": "Ornithology", "D": "Entomology"}, "answer": "C"},
    {"id": 35, "subject": "General Knowledge", "question": "Which organization is responsible for global health?", "options": {"A": "UNICEF", "B": "WHO", "C": "UNESCO", "D": "WFP"}, "answer": "B"},
    {"id": 36, "subject": "General Knowledge", "question": "The largest island in the world is?", "options": {"A": "Madagascar", "B": "Greenland", "C": "Borneo", "D": "New Guinea"}, "answer": "B"},
    {"id": 37, "subject": "General Knowledge", "question": "Who is known as the 'Father of Computers'?", "options": {"A": "Bill Gates", "B": "Charles Babbage", "C": "Alan Turing", "D": "Steve Jobs"}, "answer": "B"},
    {"id": 38, "subject": "General Knowledge", "question": "Which is the national sport of Pakistan?", "options": {"A": "Cricket", "B": "Hockey", "C": "Football", "D": "Squash"}, "answer": "B"},
    {"id": 39, "subject": "General Knowledge", "question": "The Panama Canal connects which two oceans?", "options": {"A": "Atlantic and Indian", "B": "Pacific and Atlantic", "C": "Pacific and Indian", "D": "Arctic and Pacific"}, "answer": "B"},
    {"id": 40, "subject": "General Knowledge", "question": "Which country is known as the 'Sick Man of Europe' historically?", "options": {"A": "Greece", "B": "Ottoman Empire (Turkey)", "C": "Italy", "D": "Spain"}, "answer": "B"},
    {"id": 41, "subject": "General Knowledge", "question": "The blood group known as universal donor is?", "options": {"A": "AB+", "B": "O-", "C": "A+", "D": "B-"}, "answer": "B"},
    {"id": 42, "subject": "General Knowledge", "question": "Which is the largest bird in the world?", "options": {"A": "Eagle", "B": "Ostrich", "C": "Peacock", "D": "Albatross"}, "answer": "B"},
    {"id": 43, "subject": "General Knowledge", "question": "The Suez Canal connects the Mediterranean Sea with which sea?", "options": {"A": "Red Sea", "B": "Arabian Sea", "C": "Black Sea", "D": "Caspian Sea"}, "answer": "A"},
    {"id": 44, "subject": "General Knowledge", "question": "Which country is the largest producer of tea in the world?", "options": {"A": "China", "B": "India", "C": "Kenya", "D": "Sri Lanka"}, "answer": "A"},
    {"id": 45, "subject": "General Knowledge", "question": "The headquarters of ICC (International Cricket Council) is in?", "options": {"A": "London", "B": "Dubai", "C": "Mumbai", "D": "Singapore"}, "answer": "B"},
    {"id": 46, "subject": "English", "question": "Choose the correct synonym of 'Abundant':", "options": {"A": "Scarce", "B": "Plentiful", "C": "Rare", "D": "Limited"}, "answer": "B"},
    {"id": 47, "subject": "English", "question": "Choose the correct antonym of 'Ancient':", "options": {"A": "Old", "B": "Modern", "C": "Historic", "D": "Antique"}, "answer": "B"},
    {"id": 48, "subject": "English", "question": "Fill in the blank: She ___ to the market every day.", "options": {"A": "go", "B": "goes", "C": "going", "D": "gone"}, "answer": "B"},
    {"id": 49, "subject": "English", "question": "Choose the correctly spelled word:", "options": {"A": "Recieve", "B": "Receive", "C": "Receve", "D": "Receeve"}, "answer": "B"},
    {"id": 50, "subject": "English", "question": "Identify the correct preposition: He is good ___ Mathematics.", "options": {"A": "in", "B": "at", "C": "on", "D": "with"}, "answer": "B"},
    {"id": 51, "subject": "English", "question": "Choose the plural form of 'Child':", "options": {"A": "Childs", "B": "Childes", "C": "Children", "D": "Childrens"}, "answer": "C"},
    {"id": 52, "subject": "English", "question": "Select the correct sentence:", "options": {"A": "He don't like tea.", "B": "He doesn't likes tea.", "C": "He doesn't like tea.", "D": "He not like tea."}, "answer": "C"},
    {"id": 53, "subject": "English", "question": "Choose the synonym of 'Brave':", "options": {"A": "Coward", "B": "Fearless", "C": "Weak", "D": "Timid"}, "answer": "B"},
    {"id": 54, "subject": "English", "question": "Identify the part of speech of the underlined word: She sings 'beautifully'.", "options": {"A": "Noun", "B": "Verb", "C": "Adverb", "D": "Adjective"}, "answer": "C"},
    {"id": 55, "subject": "English", "question": "Choose the antonym of 'Generous':", "options": {"A": "Kind", "B": "Stingy", "C": "Giving", "D": "Charitable"}, "answer": "B"},
    {"id": 56, "subject": "English", "question": "Fill in the blank: I have been living here ___ 2015.", "options": {"A": "for", "B": "since", "C": "from", "D": "at"}, "answer": "B"},
    {"id": 57, "subject": "English", "question": "Choose the correct passive voice: 'She writes a letter.'", "options": {"A": "A letter is written by her.", "B": "A letter was written by her.", "C": "A letter written by her.", "D": "A letter is writing by her."}, "answer": "A"},
    {"id": 58, "subject": "English", "question": "Choose the correct meaning of the idiom 'Break the ice':", "options": {"A": "To end a friendship", "B": "To start a conversation", "C": "To cause trouble", "D": "To freeze something"}, "answer": "B"},
    {"id": 59, "subject": "English", "question": "Select the correctly punctuated sentence:", "options": {"A": "Its a beautiful day.", "B": "It's a beautiful day.", "C": "Its' a beautiful day.", "D": "Its a, beautiful day."}, "answer": "B"},
    {"id": 60, "subject": "English", "question": "Choose the correct article: He is ___ honest man.", "options": {"A": "a", "B": "an", "C": "the", "D": "no article needed"}, "answer": "B"},
    {"id": 61, "subject": "English", "question": "Choose the synonym of 'Rapid':", "options": {"A": "Slow", "B": "Quick", "C": "Steady", "D": "Delayed"}, "answer": "B"},
    {"id": 62, "subject": "English", "question": "Identify the correct sentence:", "options": {"A": "Neither of the boys were present.", "B": "Neither of the boys was present.", "C": "Neither of the boys are present.", "D": "Neither of the boy was present."}, "answer": "B"},
    {"id": 63, "subject": "English", "question": "Choose the antonym of 'Optimistic':", "options": {"A": "Hopeful", "B": "Pessimistic", "C": "Positive", "D": "Confident"}, "answer": "B"},
    {"id": 64, "subject": "English", "question": "Fill in the blank: Neither the teacher nor the students ___ ready.", "options": {"A": "is", "B": "was", "C": "were", "D": "am"}, "answer": "C"},
    {"id": 65, "subject": "English", "question": "Choose the correct comparative form: This book is ___ than that one.", "options": {"A": "gooder", "B": "better", "C": "best", "D": "well"}, "answer": "B"},
    {"id": 66, "subject": "English", "question": "Choose the meaning of the idiom 'A piece of cake':", "options": {"A": "Something delicious", "B": "Something very easy", "C": "A small portion", "D": "A difficult task"}, "answer": "B"},
    {"id": 67, "subject": "English", "question": "Choose the correct word: The committee ___ its decision.", "options": {"A": "have announced", "B": "has announced", "C": "having announced", "D": "announce"}, "answer": "B"},
    {"id": 68, "subject": "English", "question": "Select the correct spelling:", "options": {"A": "Occassion", "B": "Occasion", "C": "Ocassion", "D": "Ocasion"}, "answer": "B"},
    {"id": 69, "subject": "English", "question": "Choose the synonym of 'Diligent':", "options": {"A": "Lazy", "B": "Hardworking", "C": "Careless", "D": "Slow"}, "answer": "B"},
    {"id": 70, "subject": "English", "question": "Choose the correct question tag: She is coming, ___?", "options": {"A": "isn't it", "B": "isn't she", "C": "doesn't she", "D": "is she"}, "answer": "B"},
    {"id": 71, "subject": "English", "question": "Fill in the blank: If I ___ rich, I would travel the world.", "options": {"A": "am", "B": "was", "C": "were", "D": "be"}, "answer": "C"},
    {"id": 72, "subject": "English", "question": "Choose the antonym of 'Transparent':", "options": {"A": "Clear", "B": "Opaque", "C": "Visible", "D": "Bright"}, "answer": "B"},
    {"id": 73, "subject": "English", "question": "Choose the correct conjunction: He was tired, ___ he kept working.", "options": {"A": "so", "B": "but", "C": "because", "D": "and"}, "answer": "B"},
    {"id": 74, "subject": "English", "question": "Select the correctly spelled word:", "options": {"A": "Definately", "B": "Definitly", "C": "Definitely", "D": "Definetely"}, "answer": "C"},
    {"id": 75, "subject": "English", "question": "Choose the meaning of the idiom 'Once in a blue moon':", "options": {"A": "Very often", "B": "Rarely", "C": "Every night", "D": "Regularly"}, "answer": "B"},
    {"id": 76, "subject": "Mathematics", "question": "What is 15% of 200?", "options": {"A": "20", "B": "25", "C": "30", "D": "35"}, "answer": "C"},
    {"id": 77, "subject": "Mathematics", "question": "If a shirt costs Rs. 800 after a 20% discount, what was the original price?", "options": {"A": "Rs. 900", "B": "Rs. 950", "C": "Rs. 1000", "D": "Rs. 1050"}, "answer": "C"},
    {"id": 78, "subject": "Mathematics", "question": "What is the average of 10, 20, 30, 40, and 50?", "options": {"A": "25", "B": "30", "C": "35", "D": "40"}, "answer": "B"},
    {"id": 79, "subject": "Mathematics", "question": "A train covers 60 km in 1.5 hours. What is its speed?", "options": {"A": "30 km/h", "B": "40 km/h", "C": "45 km/h", "D": "50 km/h"}, "answer": "B"},
    {"id": 80, "subject": "Mathematics", "question": "If the ratio of boys to girls is 3:2 and there are 15 boys, how many girls are there?", "options": {"A": "8", "B": "10", "C": "12", "D": "20"}, "answer": "B"},
    {"id": 81, "subject": "Mathematics", "question": "What is the simple interest on Rs. 1000 at 10% per annum for 2 years?", "options": {"A": "Rs. 100", "B": "Rs. 150", "C": "Rs. 200", "D": "Rs. 250"}, "answer": "C"},
    {"id": 82, "subject": "Mathematics", "question": "Solve: 25% of 400 + 10% of 200", "options": {"A": "110", "B": "115", "C": "120", "D": "125"}, "answer": "C"},
    {"id": 83, "subject": "Mathematics", "question": "A number is increased by 20% to become 60. What was the original number?", "options": {"A": "45", "B": "48", "C": "50", "D": "55"}, "answer": "C"},
    {"id": 84, "subject": "Mathematics", "question": "What is the square root of 144?", "options": {"A": "10", "B": "11", "C": "12", "D": "14"}, "answer": "C"},
    {"id": 85, "subject": "Mathematics", "question": "If x + 5 = 12, what is the value of x?", "options": {"A": "5", "B": "6", "C": "7", "D": "8"}, "answer": "C"},
    {"id": 86, "subject": "Mathematics", "question": "A car travels 240 km in 4 hours. How long will it take to travel 360 km at the same speed?", "options": {"A": "5 hours", "B": "6 hours", "C": "7 hours", "D": "8 hours"}, "answer": "B"},
    {"id": 87, "subject": "Mathematics", "question": "What is 3/4 expressed as a percentage?", "options": {"A": "65%", "B": "70%", "C": "75%", "D": "80%"}, "answer": "C"},
    {"id": 88, "subject": "Mathematics", "question": "The sum of two numbers is 50 and their difference is 10. What are the numbers?", "options": {"A": "20 and 30", "B": "25 and 25", "C": "15 and 35", "D": "10 and 40"}, "answer": "A"},
    {"id": 89, "subject": "Mathematics", "question": "If 5 workers can complete a job in 10 days, how many days will 10 workers take?", "options": {"A": "3 days", "B": "4 days", "C": "5 days", "D": "6 days"}, "answer": "C"},
    {"id": 90, "subject": "Mathematics", "question": "What is the value of 12 x 12?", "options": {"A": "124", "B": "134", "C": "144", "D": "154"}, "answer": "C"},
    {"id": 91, "subject": "Pakistan Studies", "question": "Pakistan came into being on?", "options": {"A": "23 March 1940", "B": "14 August 1947", "C": "27 October 1947", "D": "6 September 1965"}, "answer": "B"},
    {"id": 92, "subject": "Pakistan Studies", "question": "The Lahore Resolution was passed in which year?", "options": {"A": "1930", "B": "1940", "C": "1945", "D": "1947"}, "answer": "B"},
    {"id": 93, "subject": "Pakistan Studies", "question": "Who was the first Governor-General of Pakistan?", "options": {"A": "Liaquat Ali Khan", "B": "Muhammad Ali Jinnah", "C": "Ayub Khan", "D": "Iskander Mirza"}, "answer": "B"},
    {"id": 94, "subject": "Pakistan Studies", "question": "Which river is the longest in Pakistan?", "options": {"A": "Jhelum", "B": "Chenab", "C": "Indus", "D": "Ravi"}, "answer": "C"},
    {"id": 95, "subject": "Pakistan Studies", "question": "The Constitution of Pakistan was enacted in which year?", "options": {"A": "1956", "B": "1962", "C": "1973", "D": "1985"}, "answer": "C"},
    {"id": 96, "subject": "Islamiat", "question": "How many pillars of Islam are there?", "options": {"A": "3", "B": "4", "C": "5", "D": "6"}, "answer": "C"},
    {"id": 97, "subject": "Islamiat", "question": "The Holy Quran was revealed over a period of approximately how many years?", "options": {"A": "13 years", "B": "23 years", "C": "33 years", "D": "10 years"}, "answer": "B"},
    {"id": 98, "subject": "Islamiat", "question": "Which is the first Kalima in Islam?", "options": {"A": "Kalima Tayyab", "B": "Kalima Shahadat", "C": "Kalima Tamjeed", "D": "Kalima Tauheed"}, "answer": "A"},
    {"id": 99, "subject": "Islamiat", "question": "In which month of the Islamic calendar is fasting obligatory?", "options": {"A": "Shawwal", "B": "Ramadan", "C": "Muharram", "D": "Rajab"}, "answer": "B"},
    {"id": 100, "subject": "Islamiat", "question": "The first revelation of the Holy Quran was received in which cave?", "options": {"A": "Cave of Thawr", "B": "Cave of Hira", "C": "Cave of Uhud", "D": "Cave of Badr"}, "answer": "B"}
  ]
};

// Expose as Module 1 data
window.MODULE_1 = quizData;
})();
